name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Run tests with coverage
        run: dotnet test --configuration Release --collect:"XPlat Code Coverage"

      - name: Install reportgenerator tool
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Generate coverage report
        run: |
          # Verificar se os arquivos de cobertura realmente existem
          ls -l **/coverage/*.xml

          # Gerar o relatório de cobertura
          reportgenerator -reports:**/coverage/*.xml -targetdir:coverage-report

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage-report
